# Generated by Django 4.2.7 on 2025-06-09 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('legal', 'Legal'), ('display', 'Display'), ('social', 'Social'), ('professional', 'Professional'), ('username', 'Username')], max_length=20)),
                ('locale', models.CharField(default='en-US', max_length=10, validators=[django.core.validators.RegexValidator('^[a-z]{2}-[A-Z]{2}$', 'Invalid locale format')])),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private'), ('organization', 'Organization Only')], default='private', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'context', 'created_at'],
                'unique_together': {('user', 'context', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_fields', models.JSONField(default=list)),
                ('access_context', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='identity.identity')),
            ],
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('permission_level', models.CharField(choices=[('none', 'No Access'), ('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Full Control')], default='read', max_length=10)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='identity.identity')),
            ],
            options={
                'unique_together': {('identity', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ContextPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_priorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('user', 'context')},
            },
        ),
    ]
