# Generated by Django 4.2.7 on 2025-06-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin-only notes'),
        ),
        migrations.AddField(
            model_name='identity',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'Standard User'), ('manager', 'Manager'), ('viewer', 'Viewer Only')], default='user', max_length=20)),
                ('is_organization_admin', models.BooleanField(default=False)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_all_identities', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
